"""
Django settings for emsjango project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ""

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [

    "member",
    "board",
    "weather",
    "dress",
    "ajax",
]

MIDDLEWARE = [

]

ROOT_URLCONF = ""

TEMPLATES = [
    {
        "BACKEND": "",
        "DIRS": [BASE_DIR/'templates'],
        "APP_DIRS": True,
        "OPTIONS": {

        },
    },
]

WSGI_APPLICATION = ""


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "emsdb",
        "USER" : "ems",
        "PASSWORD" : "1234",
        "HOST" : "localhost",
        "PORT" : "3306",
    }
}
# 1. 이걸 쓰려면 마리아db를 쓸 수 있도록 설치 pip install mysqlclient 
# 2. anaconda prompt 창 
#       : BASE_DIR >> python manage.py migrate 
#       : 아무것도 없는 db에 테이블 생김


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [

]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "ko-kr"

TIME_ZONE = "Asia/Seoul"  # UTC 영국시간

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"  # css, js 파일 위치

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

import os
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# file upload URL 설정
MEDIA_URL = "/file/"
MEDIA_ROOT = os.path.join(BASE_DIR, "file")
