-- 프로그래머스 level 1, 과일로 만든 아이스크림 고르기
SELECT F.FLAVOR
FROM FIRST_HALF F 
JOIN ICECREAM_INFO I ON (F.FLAVOR=I.FLAVOR)
WHERE (I.INGREDIENT_TYPE = 'fruit_based')
    AND  (F.TOTAL_ORDER > 3000)
ORDER BY F.TOTAL_ORDER DESC;
